---
title: "The true Basics"
author: "Jeevan Patil"
date: "6 August 2015"
output: html_document
---
1. Add another line of code to that calculates the sum of 6 and 12, and hit the 'Submit Answer' button.

R code : 

3 + 4

6 + 12



2. Add another comment in the editor on the right, Calculate 6 + 12, at the appropriate location.

R code :

\# Calculate 3 + 4

3 + 4

\# Calculate 6 + 12

6 + 12



3.  Type 2^5 in the editor to calculate 2 to the power 5.
    Type 28 %% 6 to calculate 28 modulo 6.
    Click 'Submit Answer' and have a look at the R output in the console.
    Note how the # symbol is used to add comments on the R code.

R code :

\# Addition

5 + 5 

\# Subtraction

5 - 5 

\# Multiplication

3 * 5

\# Division

(5 + 5)/2 

\# Exponentiation

2^5

\# Modulo

28%%6



5. As Filip explained in the video, there are things that make R the awesome and immensely popular language that it is today. On the other hand, there are also aspects about R that are less attractive. Which of the following statements are true regarding this statistical programming language developed by Ihaka and Gentleman in the nineties?


    i. As opposed to SAS and SPSS, R is completely open-source.
    ii. R is open-source, but it's hard to share your code with others since R          uses a command-line interface.
    iii. It typically takes a long time for new and updated R packages to be            released and made available to the public.
    iv. R is easy to use, but this comes at the cost of limited graphical                abilities.
    v. R works well with large data sets, if the code is properly written and            the data fits into the working memory.


Instructions

    statements (1) and (2) are correct; the others are false.
    statements (1) and (4) are correct; the others are false.
    statements (1) and (5) are correct; the others are false.
    statements (2) and (4) are correct; the others are false.
    statements (3) and (5) are correct; the others are false.


Ans. statements (1) and (5) are correct; the others are false.



6. Complete the code in the editor such that it assigns the value 42 to the variable x in the editor. Click 'Submit Answer'. Notice that when you ask R to print x, the value 42 appears.

R code :

\# Assign the value 42 to x

x <- 42

\# Print out the value of the variable x

x



7.  Using <-, assign the value 5 to my_apples below the first comment.
    Type my_apples below the second comment. This will print out the value of         my_apples.
    Click 'Submit Answer', and look at the console: you see that the number 5 is         printed. So R now links the variable my_apples to the value 5.


R code :

\# Assign the value 5 to the variable called my_apples

my_apples <- 5

\# Print out the value of the variable my_apples

print(my_apples)



8.  Assign to my_oranges the value 6.
    Add the variables my_apples and my_oranges and have R simply print the            result.
    Combine the variables my_apples and my_oranges into a new variable my_fruit,         which is the total amount of fruits in your fruit basket.

R code :

\# Assign a value to the variables my_apples and my_oranges

my_apples <- 5

my_oranges <- 6

\# Add these two variables together and print the result

print(my_apples + my_oranges)

\# Create the variable my_fruit

my_fruit <- my_apples + my_oranges



9. List the contents of the workspace to check that the workspace is empty.
    Create a variable, horses, equal to 3.
    Create another variable, dogs, which you set to 7.
    Create a new variable, animals, that is equal to the sum of horses and dogs.
    Inspect the contents of the workspace again to see that indeed, these three       variables are available.
    Eliminate the dogs variable from the workspace.
    Finally, inspect the objects in your workspace once more to see that only         horses and animals remain.

R code :

\# Clear the entire workspace

rm(list = ls())

\# List the contents of your workspace

ls()

\# Create the variable horses

horses <- 3

\# Create the variable dogs

dogs <- 7

\# Create the variable animals

animals <- horses + dogs

\# Inspect the contents of the workspace again

ls()

\# Remove dogs from the workspace

rm(dogs)

\# Inspect the objects in your workspace once more

ls()



10. Goal : Calculate the donut volume

Create the variables r and R, equal to 2 and 6 respectively, to calculate the volume of the donut, vol_donut. Remove all the intermediary variables that you've used to calculate vol_donut such that only the variable vol_donut remains. Finally, inspect the workspace you end up with. One last tip: ?? is available in R by default as pi.


R code :

\> r <- 2

\>r

[1] 2

\> R <- 6

\> R

[1] 6

\> ar <- pi*r^2

\> ar

[1] 12.56637

\> cc <- 2\*pi*R

\> cc

[1] 37.69911

vol_donut <- ar * cc

\> vol_donut

[1] 473.741

\> rm(R,r,ar,cc)

\> ls()

[1] "vol_donut"